import type { Broadcast } from '@libs/internalTypes';

export const mockedBroadcasts: Broadcast[] = [
  {
    broadcastId: 'aaa',
    title: '[충격] 트럼프 당선',
    contentCategory: 'POLITICS',
    moodCategory: 'INTERESTING',
    tags: ['politics', 'election'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 10870,
    username: '슈카월드',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'bbb',
    title: '[데모 공유] 팀 무지개 치즈 3주차 발표',
    contentCategory: 'TECH',
    tags: ['funch', 'boostcamp'],
    moodCategory: 'FUN',
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 100,
    username: '짜왕',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ccc',
    title: '고양이 냥냥이 냥냥냥이',
    contentCategory: 'ANIMAL',
    moodCategory: 'HAPPY',
    tags: ['cat', 'cute'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 300,
    username: '모카',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ddd',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 200,
    username: '토끼',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'eee',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 300,
    username: '펭귄',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'fff',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 400,
    username: '오리',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ggg',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 500,
    username: '앵무새',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'hhh',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 600,
    username: '거북이',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'iii',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 700,
    username: '물고기',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'jjj',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 800,
    username: '물소',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'sss',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 900,
    username: '말',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tadg',
    title: '방송 제목',
    contentCategory: 'CATEGORY',
    moodCategory: 'MOOD',
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    username: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
];
