import { CONTENTS_CATEGORY, MOODS_CATEGORY } from '@libs/constants';
import type { Broadcast } from '@libs/internalTypes';

export const mockedBroadcasts: Broadcast[] = [
  {
    broadcastId: 'aaa',
    title: '[충격] 트럼프 당선',
    contentCategory: CONTENTS_CATEGORY.politics.CODE,
    moodCategory: MOODS_CATEGORY.calm.CODE,
    tags: ['politics', 'election', 'trump', 'usa', 'president'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 10870,
    userName: '슈카월드',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'aaagggggg',
    title: '[충격] 해리스 낙선',
    contentCategory: CONTENTS_CATEGORY.politics.CODE,
    moodCategory: MOODS_CATEGORY.calm.CODE,
    tags: ['politics', 'election'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1870,
    userName: '슈카월드',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'bbb',
    title: '[데모 공유] 팀 무지개 치즈 3주차 발표',
    contentCategory: CONTENTS_CATEGORY.develop.CODE,
    moodCategory: MOODS_CATEGORY.energetic.CODE,
    tags: ['funch', 'boostcamp'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 100,
    userName: '짜왕',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ccc',
    title: '고양이 냥냥이 냥냥냥이',
    contentCategory: CONTENTS_CATEGORY.dailylife.CODE,
    moodCategory: MOODS_CATEGORY.energetic.CODE,
    tags: ['cat', 'cute'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 300,
    userName: '모카',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ddd',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.cook.CODE,
    moodCategory: MOODS_CATEGORY.depressed.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 200,
    userName: '토끼',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'eee',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.game.CODE,
    moodCategory: MOODS_CATEGORY.depressed.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 300,
    userName: '펭귄',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'fff',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.economy.CODE,
    moodCategory: MOODS_CATEGORY.funny.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 400,
    userName: '오리',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'ggg',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.fishing.CODE,
    moodCategory: MOODS_CATEGORY.getking.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 500,
    userName: '앵무새',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'hhh',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.horror.CODE,
    moodCategory: MOODS_CATEGORY.getking.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 600,
    userName: '거북이',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'iii',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.house.CODE,
    moodCategory: MOODS_CATEGORY.happy.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 700,
    userName: '물고기',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'jjj',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.music.CODE,
    moodCategory: MOODS_CATEGORY.interesting.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 800,
    userName: '물소',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'jjasdgj',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.mukbang.CODE,
    moodCategory: MOODS_CATEGORY.lonely.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 800,
    userName: '물소',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'sss',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.news.CODE,
    moodCategory: MOODS_CATEGORY.lonely.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 900,
    userName: '말',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tadg',
    title: '방송 제목',
    contentCategory: CONTENTS_CATEGORY.outdoor.CODE,
    moodCategory: MOODS_CATEGORY.unknown.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tasdgdg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.outdoor.CODE,
    moodCategory: MOODS_CATEGORY.unknown.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tasdgs21245dg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.study.CODE,
    moodCategory: MOODS_CATEGORY.unknown.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tasdgs2125dg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.talk.CODE,
    moodCategory: MOODS_CATEGORY.unknown.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tdgs2125dg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.travel.CODE,
    moodCategory: MOODS_CATEGORY.interesting.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tbbbbbdgs2125dg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.virtual.CODE,
    moodCategory: MOODS_CATEGORY.getking.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'tdaaags2125dg',
    title: '방송 제목sdg',
    contentCategory: CONTENTS_CATEGORY.virtual.CODE,
    moodCategory: MOODS_CATEGORY.getking.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
  {
    broadcastId: 'cccccccccccccccccccccccc',
    title: '레이디 가가의 방송',
    contentCategory: CONTENTS_CATEGORY.virtual.CODE,
    moodCategory: MOODS_CATEGORY.getking.CODE,
    tags: ['tag1', 'tag2'],
    thumbnailUrl: 'https://via.placeholder.com/150',
    viewerCount: 1000,
    userName: '사자',
    profileImageUrl: 'https://via.placeholder.com/150',
  },
];

export const getBroadcastsByContentCategory = (contentCategory: string) => {
  return mockedBroadcasts.filter((broadcast) => broadcast.contentCategory === contentCategory);
};

export const getBroadcastsByMoodCategory = (moodCategory: string) => {
  return mockedBroadcasts.filter((broadcast) => broadcast.moodCategory === moodCategory);
};
