name: Deployment

on:
  push:
    branches:
      - main

jobs:
  funch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: funch server deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FUNCH_SSH_KEY }}
          SERVER_HOST: ${{ secrets.FUNCH_HOST }}
          SERVER_USER: ${{ secrets.FUNCH_USER }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key "${SERVER_USER}"@"${SERVER_HOST}" << EOF
            cd /root/web25-funch
            git switch main
            git pull origin main
            pm2 reload ecosystem.config.js
          EOF

  media-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: media server deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.MEDIA_SSH_KEY }}
          SERVER_HOST: ${{ secrets.MEDIA_HOST }}
          SERVER_USER: ${{ secrets.MEDIA_USER }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key "${SERVER_USER}"@"${SERVER_HOST}" << EOF
            cd /service/web25-funch
            git switch main
            git pull origin main
            cd mediaServer
            pm2 reload ecosystem.config.js
          EOF
