name: Deployment

on:
  push:
    branches:
      - main

jobs:
  funch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: funch server deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.FUNCH_HOST }}
          username: ${{ secrets.FUNCH_USER }}
          key: ${{ secrets.FUNCH_SSH_KEY }}
          script: |
            cd /root/web25-funch
            git switch main
            git pull origin main
            cd /root/web25-funch/client
            npm install
            npm run build
            cd /root/web25-funch/chatServer
            npm install
            cd /root/web25-funch/applicationServer
            npm install
            cd /root/web25-funch
            sh deploy.sh

  media-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: media server deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MEDIA_HOST }}
          username: ${{ secrets.MEDIA_USER }}
          key: ${{ secrets.MEDIA_SSH_KEY }}
          script: |
            cd /service/web25-funch
            git switch main
            git pull origin main
            cd mediaServer
            npm install
            sh deploy.sh
